# Use an official Python runtime as a parent image
FROM python:3.9-alpine

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files into the container
COPY src/ /app/src/
COPY bin/ /app/bin/

CMD ["python", "/app/bin/pull_all_tournaments.py"]